"use client";

import { useState } from "react";
import Link from "next/link";
import {
  ArrowRight, BriefcaseBusiness, Check, ChevronDown,
  CircleUserRound, Clock3, CreditCard, Gem, Info, Search,
  ShieldCheck, Sparkles, Tag, UsersRound,
} from "lucide-react";
import { Logo, SiteNavbar } from "@/components/site-navbar";

type Audience = "customers" | "individuals" | "businesses";
type Plan = { name: string; price: number; note: string; intro: string; features: string[]; color?: "green"; popular?: boolean };
type PricingSet = { eyebrow: string; title: string; accent: string; subtitle: string; plans: Plan[]; banner: string; table: { label: string; values: string[] }[]; why: string; faq: string[]; cta: string; ctaCopy: string };

const pricing: Record<Audience, PricingSet> = {
  customers: {
    eyebrow: "customers", title: "Simple pricing for", accent: "customers.", subtitle: "Browse, request, compare, book, and manage the services you need — with transparent pricing and no hidden platform fees.",
    plans: [
      { name: "Free", price: 0, note: "Everything you need", intro: "to confidently find and book services.", features: ["Browse every service", "Post up to 10 active requests", "Compare unlimited offers", "Secure payments", "Unlimited provider messaging", "Manage all your bookings", "Book recurring services", "Save favorite providers", "Booking reminders"] },
      { name: "Plus", price: 6, note: "For added convenience", intro: "Enjoy a faster, easier booking experience.", popular: true, features: ["Everything in Free", "Priority customer support", "Exclusive offers & discounts", "Faster booking experience", "Family profiles", "Flexible schedule management", "Saved preferences"] },
      { name: "Household", price: 12, note: "For families & households", intro: "Share and manage bookings across your household.", color: "green", features: ["Everything in Plus", "Up to 6 household members", "Shared bookings & history", "Multiple addresses", "Household management", "Premium customer support", "Recurring home services"] },
    ], banner: "Customers only pay the listed service price. There are no hidden booking platform fees.", why: "Why SEVEXA pricing works for customers", cta: "Ready to book with confidence?", ctaCopy: "Join thousands of customers who find trusted services, compare offers, and book with ease on SEVEXA.",
    table: [
      {label:"Browse and discover services",values:["Unlimited","Unlimited","Unlimited"]},{label:"Post service requests",values:["Up to 10 active","Unlimited","Unlimited"]},{label:"Compare offers",values:["Unlimited","Unlimited","Unlimited"]},{label:"Secure payments",values:["✓","✓","✓"]},{label:"Message service providers",values:["Unlimited","Unlimited","Unlimited"]},{label:"Recurring services",values:["✓","✓","✓"]},{label:"Saved providers & reminders",values:["✓","✓","✓"]},{label:"Manage bookings",values:["✓","✓","✓"]},{label:"Priority customer support",values:["Standard","Priority","Premium"]},{label:"Exclusive offers & discounts",values:["—","✓","✓"]},{label:"Family / Household members",values:["1 user","Up to 4","Up to 6"]},{label:"Multiple addresses",values:["1","Up to 2","Up to 5"]},
    ], faq:["Do I pay to browse services?","How do I book a service?","Can I cancel Plus anytime?","What if I’m not satisfied?","Are service prices final?","Do you offer refunds?"]
  },
  individuals: {
    eyebrow: "individuals offering services", title: "Simple pricing for", accent: "individuals offering services.", subtitle: "Freelancers, solo providers, and independent service professionals can choose a plan that helps attract leads, manage bookings, and grow their business.",
    plans: [
      { name:"Starter",price:0,note:"A strong start for",intro:"independent service providers.",features:["Create a complete professional profile","Receive 10 leads per month","Standard search visibility","Request and quote management","Unlimited customer messaging","Booking calendar","Collect customer reviews","Access to support resources"] },
      { name:"Pro",price:19,note:"For growing your business",intro:"and getting more leads.",popular:true,features:["Everything in Starter","Unlimited leads","Featured placement in search","Review insights & response tools","Advanced profile customization","Analytics & insights","Priority support"] },
      { name:"Premium",price:39,note:"For top-performing",intro:"individual providers.",color:"green",features:["Everything in Pro","Boosted visibility","Premium badge on profile","Recurring customer tools","Advanced booking controls","Custom offers & promotions","Deeper analytics","Premium support"] },
    ], banner:"Customers can browse for free. You only pay for the plan you choose—with transparent pricing and no hidden fees.", why:"Why SEVEXA pricing works for service providers",cta:"Ready to grow your service business?",ctaCopy:"Join thousands of independent service providers who are getting more leads, bookings, and loyal customers on SEVEXA.",
    table:[{label:"Monthly cost",values:["€0 /month","€19 /month","€39 /month"]},{label:"Leads per month",values:["10 leads","Unlimited","Unlimited"]},{label:"Profile visibility",values:["Standard","Enhanced","Boosted"]},{label:"Customer messaging",values:["Unlimited","Unlimited","Unlimited"]},{label:"Booking calendar",values:["✓","✓","✓"]},{label:"Featured placement in search",values:["—","✓","✓"]},{label:"Collect customer reviews",values:["✓","✓","✓"]},{label:"Review insights & response tools",values:["—","✓","✓"]},{label:"Analytics & insights",values:["—","Basic","Advanced"]},{label:"Recurring customer tools",values:["—","—","✓"]},{label:"Booking controls",values:["Basic","Advanced","Advanced+"]},{label:"Custom offers & promotions",values:["—","—","✓"]},{label:"Support level",values:["Standard","Priority","Premium"]},{label:"Premium badge",values:["—","—","✓"]}],
    faq:["Can I change plans later?","Can I cancel anytime?","How do leads work?","What happens to my profile if I downgrade?","Do I pay per booking?","Do you take a commission?"]
  },
  businesses: {
    eyebrow:"professionals & businesses",title:"Simple pricing for",accent:"every path.",subtitle:"Whether you’re looking for trusted services, offering your skills independently, or running a growing business — SEVEXA gives you the tools to thrive.",
    plans:[
      {name:"Starter",price:0,note:"A capable foundation for",intro:"new professionals and small teams.",features:["Create a branded professional profile","Receive up to 20 leads per month","Standard profile visibility","Requests, quotes, and bookings","Unlimited customer messaging","Collect customer reviews","Basic performance dashboard","Access to support resources"]},
      {name:"Pro",price:19,note:"Grow your business and",intro:"get more quality leads.",popular:true,features:["Everything in Starter","Unlimited leads","Featured placement in search","Review management tools","Advanced profile customization","Enhanced analytics & insights","Priority customer support"]},
      {name:"Business",price:49,note:"Scale your operations with",intro:"advanced tools and support.",color:"green",features:["Everything in Pro","Team members & roles","Advanced analytics & reporting","Branded business profile","Lead routing & assignment","Premium priority support"]},
    ],banner:"Good news! Customers looking for and booking services on SEVEXA can use the platform completely free.",why:"Why SEVEXA pricing works",cta:"Ready to grow your business with SEVEXA?",ctaCopy:"Join thousands of professionals already building their success on SEVEXA.",
    table:[{label:"Monthly cost",values:["€0","€19 /month","€49 /month"]},{label:"Leads per month",values:["Up to 20","Unlimited","Unlimited"]},{label:"Profile visibility",values:["Standard","Enhanced","Maximum"]},{label:"Requests, quotes & bookings",values:["✓","✓","✓"]},{label:"Customer messaging",values:["Unlimited","Unlimited","Unlimited"]},{label:"Collect customer reviews",values:["✓","✓","✓"]},{label:"Featured placement",values:["—","✓","✓"]},{label:"Review management tools",values:["—","✓","✓"]},{label:"Analytics & insights",values:["Basic","Enhanced","Advanced"]},{label:"Team members",values:["—","—","Up to 10 included"]},{label:"Lead routing & assignment",values:["—","—","✓"]},{label:"Priority support",values:["Standard","Priority","Premium"]},{label:"Custom branding",values:["—","—","✓"]}],faq:["Can I change plans later?","What happens if I cancel?","Do customers pay to use SEVEXA?","How do leads and billing work?","Are there hidden fees?","Do you offer refunds?"]
  }
};

const tabs: {id:Audience; label:string; icon:typeof Search}[] = [
  {id:"customers",label:"For customers",icon:Search},{id:"individuals",label:"For individuals offering services",icon:CircleUserRound},{id:"businesses",label:"For professionals & businesses",icon:UsersRound}
];

function Footer(){return <footer className="mt-8 border-t bg-white"><div className="pricing-shell grid gap-8 py-10 sm:grid-cols-2 lg:grid-cols-6"><div><Logo/><p className="mt-4 text-xs leading-5 text-slate-500">Find it, book it, get it done.<br/>Trusted services, local and on demand.</p></div>{[["Explore","All services","Popular services","Local services","Categories"],["For customers","How it works","Pricing","Safety & trust","Help center"],["Company","About us","Careers","Press","Partnerships"],["Support","Help center","Contact us","Safety & trust","Community"]].map(([h,...x])=><div key={h}><b className="font-serif text-sm">{h}</b>{x.map(i=><a className="mt-2 block text-xs text-slate-500" href="#" key={i}>{i}</a>)}</div>)}<div><b className="font-serif text-sm">Stay in the loop</b><p className="mt-2 text-xs leading-5 text-slate-500">Get tips, updates, and offers straight to your inbox.</p><div className="mt-3 flex rounded-full border p-1"><input className="min-w-0 flex-1 bg-transparent px-3 text-xs outline-none" aria-label="Email" placeholder="Enter your email"/><button aria-label="Subscribe" className="grid size-8 place-items-center rounded-full bg-[#511482] text-white"><ArrowRight size={14}/></button></div></div></div><div className="border-t"><div className="pricing-shell flex flex-wrap justify-between gap-3 py-5 text-[11px] text-slate-500"><span>© 2026 SEVEXA. All rights reserved.</span><span>Terms of Service　　Privacy Policy　　Cookie Policy　　English⌄</span></div></div></footer>}

export default function PricingPage(){
  const [audience,setAudience]=useState<Audience>("customers"); const data=pricing[audience];
  return <main className="min-h-screen bg-[#fffefd] text-[#101428]"><SiteNavbar active="pricing"/><div className="pricing-shell">
    <section className="pb-9 pt-12 text-center sm:pt-16 lg:pt-20"><h1 className="font-serif text-[clamp(2.75rem,5vw,4.5rem)] font-semibold leading-[1.03] tracking-[-.035em]">{data.title} <span className="text-[#511482]">{data.accent}</span></h1><p className="mx-auto mt-5 max-w-3xl text-[15px] leading-6 text-[#4c5060]">{data.subtitle}</p></section>
    <div className="mx-auto grid max-w-[1040px] gap-1 rounded-2xl border border-[#e8e3eb] bg-[#f7f5f8] p-1.5 shadow-[0_8px_24px_rgba(35,20,45,.08)] md:grid-cols-3" role="tablist" aria-label="Pricing audiences">{tabs.map(({id,label,icon:Icon})=>{const selected=audience===id;return <button key={id} id={`pricing-tab-${id}`} role="tab" aria-selected={selected} aria-controls="pricing-plans" tabIndex={selected?0:-1} onClick={()=>setAudience(id)} className={`flex min-h-14 items-center justify-center gap-3 rounded-xl border px-4 text-sm font-semibold transition-all duration-200 focus-visible:z-10 ${selected?"border-[#6a2798] bg-white text-[#511482] shadow-[0_3px_10px_rgba(69,25,98,.12)]":"border-transparent text-[#34303b] hover:bg-white/70 hover:text-[#511482]"}`}><Icon size={20} strokeWidth={1.8}/>{label}</button>})}</div>
    <section id="pricing-plans" role="tabpanel" aria-labelledby={`pricing-tab-${audience}`} className="mx-auto mt-10 grid max-w-[1240px] gap-6 lg:grid-cols-3">{data.plans.map((plan,i)=><article key={plan.name} className={`relative flex min-h-[500px] flex-col rounded-2xl border bg-white p-7 shadow-[0_8px_28px_rgba(41,25,48,.065)] sm:p-8 ${plan.popular?"border-[#6925a0] ring-1 ring-[#6925a0]":"border-[#e5e3e6]"}`}>{plan.popular&&<span className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-[#4b0c79] px-4 py-1 text-[9px] font-bold tracking-wide text-white">MOST POPULAR</span>}<div className="flex gap-5"><span className={`grid size-16 shrink-0 place-items-center rounded-2xl ${plan.color?"bg-[#edf5f0] text-[#176849]":"bg-[#f5effa] text-[#55208a]"}`}>{i===1?<Sparkles size={32}/>:i===2?<BriefcaseBusiness size={30}/>:<Gem size={30}/>}</span><div><h2 className="font-serif text-2xl font-semibold">{plan.name}</h2><p className="mt-1 text-sm font-medium leading-5">{plan.note}<br/>{plan.intro}</p></div></div><p className={`mt-7 font-serif text-5xl ${plan.color?"text-[#176849]":"text-[#4e1280]"}`}>€{plan.price}<span className="font-sans text-sm text-black"> /month</span></p><ul className="mt-7 space-y-3.5 pb-8 text-sm">{plan.features.map(x=><li key={x} className="flex gap-2.5"><Check className={`mt-px size-4 shrink-0 rounded-full p-[2px] text-white ${plan.color?"bg-[#187052]":"bg-[#511482]"}`}/>{x}</li>)}</ul><button className={`mt-auto h-12 shrink-0 rounded-full border text-sm font-semibold transition hover:-translate-y-0.5 hover:shadow-md ${plan.popular?"border-transparent bg-gradient-to-r from-[#451078] to-[#68159c] text-white":plan.color?"border-[#24795c] text-[#176849]":"border-[#632298] text-[#531385]"}`}>{plan.price===0?"Start for free":`Get ${plan.name}`}</button></article>)}</section>
    <p className="mx-auto mt-5 flex max-w-3xl items-center justify-center gap-3 rounded-lg bg-[#f6f5f3] px-4 py-3 text-center text-xs"><ShieldCheck className="size-5 shrink-0 fill-[#187052] text-white"/>{data.banner}</p>
    <section className="mt-5 overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[680px] border-collapse text-center text-[11px]"><thead><tr>{["All features",...data.plans.map(x=>x.name)].map((x,i)=><th className={`border-b px-4 py-3 font-serif text-base ${i===2?"bg-[#fcf8ff]":""}`} key={x}>{x}</th>)}</tr></thead><tbody>{data.table.map(row=><tr key={row.label} className="border-b last:border-0"><td className="px-5 py-2 text-left"><Info className="mr-3 inline size-4 text-[#632298]"/>{row.label}</td>{row.values.map((v,i)=><td key={i} className={`px-4 py-2 ${i===1?"bg-[#fcf8ff]":""} ${v==="✓"?(i===2?"text-lg text-[#176849]":"text-lg text-[#511482]"):""}`}>{v}</td>)}</tr>)}</tbody></table></section>
    <h2 className="mt-7 text-center font-serif text-2xl font-semibold">{data.why}</h2><section className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Tag,"No setup fees","Get started instantly with clear, upfront costs."],[Clock3,"Cancel anytime","Change or cancel whenever you need."],[ShieldCheck,"Secure payments","Your payments and data are always protected."],[CreditCard,"Transparent pricing","No hidden fees—what you see is what you pay."]].map(([Icon,title,copy],i)=><article key={title as string} className="flex gap-4 rounded-xl border bg-white p-5"><span className={`grid size-12 shrink-0 place-items-center rounded-full ${i%2?"bg-[#edf5f0] text-[#176849]":"bg-[#f5effa] text-[#55208a]"}`}><Icon size={23}/></span><div><h3 className="font-serif text-sm font-semibold">{title as string}</h3><p className="mt-2 text-[10px] leading-4 text-slate-600">{copy as string}</p></div></article>)}</section>
    <h2 className="mt-10 text-center font-serif text-3xl font-semibold">Frequently asked questions</h2><section className="mx-auto mt-5 grid max-w-[1240px] gap-3 md:grid-cols-2">{data.faq.map(q=><details key={q} className="group rounded-xl border bg-white px-5 py-4 shadow-[0_2px_8px_rgba(41,25,48,.03)]"><summary className="flex cursor-pointer list-none items-center justify-between font-serif text-sm font-semibold">{q}<ChevronDown className="size-4 transition group-open:rotate-180"/></summary><p className="pt-3 text-xs leading-5 text-slate-600">Yes. SEVEXA plans are flexible, transparent, and designed to change as your needs grow.</p></details>)}</section>
    <section className="relative my-5 overflow-hidden rounded-xl bg-gradient-to-r from-[#35105f] via-[#51177c] to-[#1c2739] px-8 py-8 text-white sm:px-12"><div className="relative z-10 max-w-lg"><h2 className="font-serif text-3xl leading-tight">{data.cta}</h2><p className="mt-3 text-sm leading-6 text-white/80">{data.ctaCopy}</p><div className="mt-6 flex flex-wrap gap-4"><Link href="#" className="rounded-full bg-white px-6 py-3 text-xs font-bold text-[#481475]">Start free <ArrowRight className="ml-5 inline size-4"/></Link><Link href="#" className="rounded-full border border-white/70 px-6 py-3 text-xs font-bold">Explore plans <ArrowRight className="ml-5 inline size-4"/></Link></div></div><div className="absolute -bottom-12 right-5 hidden h-52 w-[40%] rotate-2 rounded-xl border-8 border-[#24232a] bg-white p-5 text-[#172035] shadow-2xl md:block"><b className="text-xs">Good morning, Alex!</b><div className="mt-5 grid grid-cols-3 gap-2">{["Leads","Bookings","Revenue"].map((x,i)=><div className="rounded bg-slate-50 p-2 text-[9px]" key={x}>{x}<b className="block text-sm">{[248,1402,"€5,430"][i]}</b></div>)}</div><div className="mt-4 h-16 rounded bg-gradient-to-t from-purple-100 to-transparent"/></div></section>
  </div><Footer/></main>
}